export const UI = {
  en: {
    appName: "LexAI",
    tagline: "Legal Document Intelligence",
    upload: "Drop document here or click to upload",
    uploadSub: "PDF, DOCX, DOC, TXT, RTF — or paste text below",
    paste: "Or paste document text here...",
    analyze: "Analyze Document ↗",
    analyzing: "Analyzing...",
    tabs: ["Risk Checklist", "Comments", "Legal References", "Summary", "AI Consultant"],
    proceduralTabs: ["Position", "Evidence", "Counterarguments", "Prospects"],
    docType: "Document type",
    jurisdiction: "Jurisdiction",
    language: "Language",
    chat: "Ask the AI consultant...",
    send: "Send",
    upgrade: "Upgrade to Pro",
    proFeature: "Pro feature — upgrade to unlock",
    trialLeft: "2 analyses remaining in free trial",
    plans: ["Free", "Pro", "Enterprise"],
    planDesc: [
      "2 analyses/mo\nBasic checklist\n1 jurisdiction",
      "Unlimited analyses\nFull analysis\nAll jurisdictions\nAI consultant\nExport PDF",
      "Team access\nAPI integration\nCustom jurisdictions\nPriority support\nSLA",
    ],
    planPrice: ["$0", "$29/mo", "$199/mo"],
    noDoc: "Upload or paste a document to begin analysis.",
    summaryVerdict: "Overall verdict",
    summaryKeyIssues: "Key issues",
    summaryRecommendation: "Recommendation",
    summaryDisclaimer: "⚠ This analysis is for informational purposes only and does not constitute legal advice. Consult a licensed attorney before taking any legal action.",
  },
  ru: {
    appName: "LexAI",
    tagline: "Анализ юридических документов",
    upload: "Перетащите документ сюда или нажмите для загрузки",
    uploadSub: "PDF, DOCX, DOC, TXT, RTF — или вставьте текст ниже",
    paste: "Или вставьте текст документа здесь...",
    analyze: "Анализировать документ ↗",
    analyzing: "Анализируем...",
    tabs: ["Чек-лист рисков", "Комментарии", "Правовые ссылки", "Резюме", "ИИ Консультант"],
    proceduralTabs: ["Позиция", "Доказательства", "Контраргументы", "Перспективы"],
    docType: "Тип документа",
    jurisdiction: "Юрисдикция",
    language: "Язык",
    chat: "Задайте вопрос ИИ-консультанту...",
    send: "Отправить",
    upgrade: "Перейти на Pro",
    proFeature: "Функция Pro — обновитесь для доступа",
    trialLeft: "Осталось 2 анализа в бесплатном плане",
    plans: ["Free", "Pro", "Enterprise"],
    planDesc: [
      "2 анализа/мес\nБазовый чек-лист\n1 юрисдикция",
      "Неограниченно\nПолный анализ\nВсе юрисдикции\nИИ-консультант\nЭкспорт PDF",
      "Командный доступ\nAPI интеграция\nСвои юрисдикции\nПриоритетная поддержка\nSLA",
    ],
    planPrice: ["$0", "$29/мес", "$199/мес"],
    noDoc: "Загрузите или вставьте документ для начала анализа.",
    summaryVerdict: "Общий вывод",
    summaryKeyIssues: "Ключевые проблемы",
    summaryRecommendation: "Рекомендация",
    summaryDisclaimer: "⚠ Данный анализ носит исключительно информационный характер и не является юридической консультацией. Перед принятием юридически значимых решений обратитесь к лицензированному юристу.",
  },
  de: {
    appName: "LexAI",
    tagline: "Intelligente Rechtsdokumentanalyse",
    upload: "Dokument hier ablegen oder klicken zum Hochladen",
    uploadSub: "PDF, DOCX, DOC, TXT, RTF — oder Text unten einfügen",
    paste: "Oder Dokumenttext hier einfügen...",
    analyze: "Dokument analysieren ↗",
    analyzing: "Analysiere...",
    tabs: ["Risikoliste", "Kommentare", "Rechtsquellen", "Zusammenfassung", "KI-Berater"],
    proceduralTabs: ["Position", "Beweise", "Gegenargumente", "Aussichten"],
    docType: "Dokumenttyp",
    jurisdiction: "Jurisdiktion",
    language: "Sprache",
    chat: "Fragen Sie den KI-Berater...",
    send: "Senden",
    upgrade: "Auf Pro upgraden",
    proFeature: "Pro-Funktion — upgraden zum Freischalten",
    trialLeft: "2 Analysen verbleibend im kostenlosen Plan",
    plans: ["Free", "Pro", "Enterprise"],
    planDesc: [
      "2 Analysen/Monat\nGrundliste\n1 Jurisdiktion",
      "Unbegrenzte Analysen\nVollständige Analyse\nAlle Jurisdiktionen\nKI-Berater\nPDF-Export",
      "Team-Zugang\nAPI-Integration\nEigene Jurisdiktionen\nPrioritätssupport\nSLA",
    ],
    planPrice: ["$0", "$29/Monat", "$199/Monat"],
    noDoc: "Laden Sie ein Dokument hoch oder fügen Sie Text ein, um die Analyse zu starten.",
    summaryVerdict: "Gesamturteil",
    summaryKeyIssues: "Kernprobleme",
    summaryRecommendation: "Empfehlung",
    summaryDisclaimer: "⚠ Diese Analyse dient ausschließlich Informationszwecken und stellt keine Rechtsberatung dar. Wenden Sie sich vor rechtlichen Schritten an einen zugelassenen Rechtsanwalt.",
  },
  fr: {
    appName: "LexAI",
    tagline: "Intelligence Juridique des Documents",
    upload: "Déposez le document ici ou cliquez pour télécharger",
    uploadSub: "PDF, DOCX, DOC, TXT, RTF — ou collez le texte ci-dessous",
    paste: "Ou collez le texte du document ici...",
    analyze: "Analyser le document ↗",
    analyzing: "Analyse en cours...",
    tabs: ["Liste des risques", "Commentaires", "Références légales", "Résumé", "Consultant IA"],
    proceduralTabs: ["Position", "Preuves", "Contre-arguments", "Perspectives"],
    docType: "Type de document",
    jurisdiction: "Juridiction",
    language: "Langue",
    chat: "Posez une question au consultant IA...",
    send: "Envoyer",
    upgrade: "Passer à Pro",
    proFeature: "Fonctionnalité Pro — mettez à niveau pour débloquer",
    trialLeft: "2 analyses restantes dans le plan gratuit",
    plans: ["Free", "Pro", "Enterprise"],
    planDesc: [
      "2 analyses/mois\nListe de base\n1 juridiction",
      "Analyses illimitées\nAnalyse complète\nToutes juridictions\nConsultant IA\nExport PDF",
      "Accès équipe\nIntégration API\nJuridictions personnalisées\nSupport prioritaire\nSLA",
    ],
    planPrice: ["$0", "$29/mois", "$199/mois"],
    noDoc: "Téléchargez ou collez un document pour commencer l'analyse.",
    summaryVerdict: "Verdict global",
    summaryKeyIssues: "Points clés",
    summaryRecommendation: "Recommandation",
    summaryDisclaimer: "⚠ Cette analyse est fournie à titre informatif uniquement et ne constitue pas un conseil juridique. Consultez un avocat agréé avant de prendre toute décision juridique.",
  },
  zh: {
    appName: "LexAI",
    tagline: "法律文件智能分析",
    upload: "将文件拖放到此处或点击上传",
    uploadSub: "PDF、DOCX、DOC、TXT、RTF — 或在下方粘贴文本",
    paste: "或在此处粘贴文档文本...",
    analyze: "分析文件 ↗",
    analyzing: "分析中...",
    tabs: ["风险清单", "评论", "法律依据", "摘要", "AI顾问"],
    proceduralTabs: ["立场", "证据", "反驳", "前景"],
    docType: "文件类型",
    jurisdiction: "司法管辖区",
    language: "语言",
    chat: "向AI顾问提问...",
    send: "发送",
    upgrade: "升级到Pro",
    proFeature: "Pro功能 — 升级以解锁",
    trialLeft: "免费计划剩余2次分析",
    plans: ["免费", "专业版", "企业版"],
    planDesc: [
      "2次分析/月\n基础清单\n1个司法管辖区",
      "无限分析\n完整分析\n所有司法管辖区\nAI顾问\n导出PDF",
      "团队访问\nAPI集成\n自定义司法管辖区\n优先支持\nSLA",
    ],
    planPrice: ["$0", "$29/月", "$199/月"],
    noDoc: "上传或粘贴文档以开始分析。",
    summaryVerdict: "总体评价",
    summaryKeyIssues: "关键问题",
    summaryRecommendation: "建议",
    summaryDisclaimer: "⚠ 本分析仅供参考，不构成法律建议。在采取任何法律行动之前，请咨询持牌律师。",
  },
  es: {
    appName: "LexAI",
    tagline: "Inteligencia Jurídica de Documentos",
    upload: "Arrastre el documento aquí o haga clic para cargar",
    uploadSub: "PDF, DOCX, DOC, TXT, RTF — o pegue el texto abajo",
    paste: "O pegue el texto del documento aquí...",
    analyze: "Analizar documento ↗",
    analyzing: "Analizando...",
    tabs: ["Lista de riesgos", "Comentarios", "Referencias legales", "Resumen", "Consultor IA"],
    proceduralTabs: ["Posición", "Pruebas", "Contraargumentos", "Perspectivas"],
    docType: "Tipo de documento",
    jurisdiction: "Jurisdicción",
    language: "Idioma",
    chat: "Pregúntele al consultor IA...",
    send: "Enviar",
    upgrade: "Actualizar a Pro",
    proFeature: "Función Pro — actualice para desbloquear",
    trialLeft: "2 análisis restantes en el plan gratuito",
    plans: ["Free", "Pro", "Enterprise"],
    planDesc: [
      "2 análisis/mes\nLista básica\n1 jurisdicción",
      "Análisis ilimitados\nAnálisis completo\nTodas las jurisdicciones\nConsultor IA\nExportar PDF",
      "Acceso en equipo\nIntegración API\nJurisdicciones propias\nSoporte prioritario\nSLA",
    ],
    planPrice: ["$0", "$29/mes", "$199/mes"],
    noDoc: "Cargue o pegue un documento para comenzar el análisis.",
    summaryVerdict: "Veredicto general",
    summaryKeyIssues: "Problemas clave",
    summaryRecommendation: "Recomendación",
    summaryDisclaimer: "⚠ Este análisis es solo informativo y no constituye asesoramiento legal. Consulte a un abogado con licencia antes de tomar medidas legales.",
  },
};

export const t = (lang, key) => (UI[lang] || UI.en)[key] || UI.en[key];
